name: Prober Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - 'cmd/prober/**'

permissions:
  contents: read

jobs:
  prober-test:
    name: 'Prober test'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Checkout'
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.21'
          check-latest: true

      - name: Prober test
        id: prober-test
        run: go run ./cmd/prober --one-time --write-prober --logStyle dev
